// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niyqtjsukjrfoprdzmly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5peXF0anN1a2pyZm9wcmR6bWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODQ0MzAsImV4cCI6MjA2MDg2MDQzMH0.IhCZbb8ZGRrZcKrygbEKLiNCy9633pTw4wbjhpwhq0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);